[package]
name = "gpu-rdma-runtime"
version = "0.1.0"
edition = "2021"
autobins = false

[features]
default = []

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.4", features = ["derive", "env"] }
libloading = "0.8"
rdma-mummy-sys = "0.2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sideway = "0.4.1"
rand = "0.8"

[[bin]]
name = "rdma_test_client"
path = "src/bin/rdma_test_client.rs"

[[bin]]
name = "rdma_gpu_server"
path = "src/bin/rdma_gpu_server.rs"
# required-features = ["cuda"]
